### ISSUE TITLE
📋 [TASK] - Update Gen-Gherkin Plugin Tests

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#10]
### Parent Feature

#1

### Task Description

As an AaC Tester, I want to update the plugin tests to leverage the updated plugin, so that I am confident in providing a robust and reliable plugin to end users.

### Acceptance Criteria

- [ ] Include "happy path" tests
- [ ] Include "sad path" tests
- [ ] Include behavior feature file tests
- [ ] Include feature file unit tests to evaluate output.
