### ISSUE TITLE
Move Legacy Gen-Gherkin to New Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#2]
### Parent Feature
#1 

### Task Description
As an AaC Developer, I need to copy the legacy `gen-gherkin` plugin from PreAPI repository to the new aac-gherkin repository, so that it is properly separated from core baseline to work the refactor efforts.

Legacy: https://github.com/DevOps-MBSE/AaC-PreAPIChange

New: https://github.com/DevOps-MBSE/aac-gherkin

### Acceptance Criteria
- [ ] Documentation of `gen-gherkin` is moved to the new repository.
- [ ] Plugin directory for `gen-gherkin` is moved to the new repository.
- [ ] Unit tests for `gen-gherkin` is moved to the new repository.
