### ISSUE TITLE
📋 [TASK] - Standardize Docker Files

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#20]
### Parent Feature

https://github.com/DevOps-MBSE/AaC/issues/909

### Task Description

As an AaC CI/CD Developer, I want to determine the proper standardization for the repository Docker files, so that I can provide a consistent and reliable container for development efforts.

### Acceptance Criteria

- [x] Investigate differences between repository Docker files
- [x] Make necessary configuration changes for a central Docker file
- [ ] Confirm Gitpod from any repository can use the central configuration
