### ISSUE TITLE
📋 [TASK] - Dictionary Boilerplate Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#21]
### Parent Feature

https://github.com/DevOps-MBSE/AaC/issues/928

### Task Description

As an AaC Developer, I want to create an initial dictionary boilerplate template, so that I can assist end users in providing more consistent dictionary files to work with automated test framework.

### Acceptance Criteria

- [ ] Template includes identified boilerplate variables
- [ ] Template includes identified boilerplate methods
- [ ] Template includes identified boilerplate docstrings
- [ ] Template includes identified boilerplate comments
- [ ] Any additional identified boilerplate categories from users
- [ ] Incorporated to be called via a new command.
