### ISSUE TITLE
Implement Project Infrastructure in New AaC-Gherkin Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#3]
### Parent Feature
#1 

### Task Description
As an AaC Developer, I want my project infrastructure implemented within the aac-gherkin repository, so that I provide a consistent and quality plugin.

### Acceptance Criteria
- [ ] Include pertinent pieces from `/.github` directory.
  - [ ] Include pertinent workflows for pipelines.
  - [ ] Include pertinent issue templates for requests and tracking.
    - [ ] Update to reference new repository housing location. 
- [ ] Include pertinent documentation requirements and configurations.
  - [ ] Ensure from the `/docs` directory that the necessary documentation configurations and structure were brought over.
- [ ] Include pertinent project requirements and configurations.
  - [ ] Root level configuration and infrastructure pieces, i.e. `setup.py` or `pyproject.toml`.
- [ ] Configure repository for proper permissions.
  - [ ] Match configuration of core AaC Repo.
