### ISSUE TITLE
Register Gen-Gherkin Plugin with Plugin Manager

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#5]
### Parent Feature
#1 

### Task Description
As an AaC Developer, I want to update the rest-api plugin to use the new API, so that I provide an updated version of the capability. 

### Acceptance Criteria

- [ ] Utilize the `gen-project` and `gen-plugin` commands from AaC to create all boilerplate files.
- [ ] Ensure entry point is properly configured for plugin registration. 
- [ ] Detect gen-gherkin command from plugin and display within core AaC available commands.
