### ISSUE TITLE
Update Gen-Gherkin Feature File Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-gen-gherkin#8]
### Parent Feature

#1 

### Task Description

As an AaC Developer, I want to update the `gen-puml` `puml-sequence` diagram templates, so that I have a correct and consistent diagram returned to end users.

### Acceptance Criteria

- [ ] Feature file template is updated to use AaC `generate` helper functions as necessary.
- [ ] Feature file template is updated to use the new definition object.
- [ ] Feature file template is updated to meet output needs.
